name: format Check
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src/Parser'
          - 'src/Engine'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
        fallback-style: 'Google' # optional
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install dotnet-format tool
      run: dotnet tool install -g dotnet-format
    
    - name: Run dotnet format
      run: dotnet format '.\src\Editor' --folder --check --verbosity diagnostic     
      
      
